#!/usr/bin/env bash

a=1
b=2

if [[ $a == $b ]]; then
  echo 'a and b are the same'
elif [[ $a != $b ]]; then
  echo 'a and b are not the same'
fi

while [[ -f file.txt ]]; do
  echo 'file.txt exists and is a regular file'
done
# an infinite loop
